<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>Exe</OutputType>
		<TargetFramework>net10.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
	</PropertyGroup>

	<ItemGroup>
	  <PackageReference Include="DevBrewLabs.Parserly" Version="1.0.1" />
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\DevBrewLabs.Evalis\DevBrewLabs.Evalis.csproj" />
	</ItemGroup>

</Project>